#!/usr/bin/env python3

from smtplib import SMTP as Client
client = Client("0.0.0.0", 2525)
r = client.sendmail('from@from.com', ['to@to.com'], """From: Anne Person <from@from.com>
To: Bart Person <to@to.com>
Subject: Guillaume pas beau

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc id cursus metus aliquam eleifend mi. Amet consectetur adipiscing elit duis tristique sollicitudin. Nunc sed augue lacus viverra vitae congue eu. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Vitae semper quis lectus nulla at volutpat. Sit amet venenatis urna cursus eget nunc. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Eu non diam phasellus vestibulum. Placerat vestibulum lectus mauris ultrices eros in cursus. Pulvinar pellentesque habitant morbi tristique. Risus in hendrerit gravida rutrum quisque. Nibh praesent tristique magna sit amet purus gravida quis blandit. Eget magna fermentum iaculis eu non diam. Ut sem nulla pharetra diam sit amet nisl suscipit. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Mattis enim ut tellus elementum sagittis vitae et leo duis. Iaculis eu non diam phasellus vestibulum lorem sed risus.

Volutpat sed cras ornare arcu. Cras ornare arcu dui vivamus arcu. Nunc lobortis mattis aliquam faucibus purus in massa tempor. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Feugiat vivamus at augue eget. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. In fermentum et sollicitudin ac orci phasellus egestas tellus. Morbi quis commodo odio aenean. Aliquet risus feugiat in ante metus. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Adipiscing elit pellentesque habitant morbi. Aliquet eget sit amet tellus. Enim tortor at auctor urna nunc id cursus metus. Fermentum leo vel orci porta non pulvinar neque laoreet. Lorem dolor sed viverra ipsum nunc aliquet. Mi sit amet mauris commodo quis imperdiet massa. Eget duis at tellus at urna condimentum mattis pellentesque. Vulputate sapien nec sagittis aliquam. Tellus orci ac auctor augue mauris augue. Tortor dignissim convallis aenean et tortor at risus viverra.

Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Leo urna molestie at elementum eu facilisis sed odio. Interdum velit laoreet id donec ultrices. Condimentum lacinia quis vel eros. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Ac ut consequat semper viverra nam libero. Posuere sollicitudin aliquam ultrices sagittis orci a. Porta nibh venenatis cras sed felis eget velit aliquet sagittis. Dolor sit amet consectetur adipiscing elit pellentesque. Commodo elit at imperdiet dui accumsan sit amet. Sed vulputate odio ut enim blandit volutpat. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Amet nisl purus in mollis nunc sed id semper. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Et tortor consequat id porta nibh venenatis.

Dolor morbi non arcu risus. Sagittis orci a scelerisque purus semper eget duis. In mollis nunc sed id semper risus in hendrerit. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Enim facilisis gravida neque convallis a cras semper auctor neque. Non odio euismod lacinia at quis risus sed. Ultrices dui sapien eget mi proin sed libero. Suspendisse sed nisi lacus sed. Laoreet id donec ultrices tincidunt. Vehicula ipsum a arcu cursus vitae. Amet nisl purus in mollis nunc sed id semper risus. Mattis vulputate enim nulla aliquet porttitor. Vitae et leo duis ut diam quam. Suspendisse potenti nullam ac tortor. Pulvinar neque laoreet suspendisse interdum consectetur. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Tellus elementum sagittis vitae et. Dolor morbi non arcu risus.

Mauris rhoncus aenean vel elit scelerisque mauris. Velit laoreet id donec ultrices tincidunt arcu. Lacus vestibulum sed arcu non. Eget nullam non nisi est sit. Id aliquet lectus proin nibh nisl condimentum. Turpis in eu mi bibendum neque. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Adipiscing enim eu turpis egestas pretium. Eu augue ut lectus arcu. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Magna ac placerat vestibulum lectus mauris ultrices. Posuere urna nec tincidunt praesent semper feugiat nibh sed. Bibendum ut tristique et egestas. In cursus turpis massa tincidunt dui.
""")
print(r)